apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet # Adjust if you're using a different controller
    name: mongodb
  minReplicas: 1
  maxReplicas: 5 # Adjust as needed
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Adjust as needed
